library(bayesdfa)
library(tidyverse)
library(ggplot2)
library(readr) # faster writing
library(data.table) # faster writing of large files
library(lubridate)
library(mgcv)
library(MuMIn)
library(corrplot)
library(car)
library(ggpubr)
library(fst)
library(viridis)
library(ggbeeswarm)
library(gratia)
df.subset <- envir_data[, names(envir_data)[(names(envir_data) %in% unique(margtop5$cov))]]
corrplotsat<-cor(df.subset)
corrplot.mixed(corrplotsat)
colSums(corrplotsat)

corr2<-cor(envir_data%>%select(ONIpjuv,CutiSTIpjuv,MLDpart,LSTlarv))
best<-gam(Y_rec~s(ONIpjuv,k=3)+s(CutiSTIpjuv,k=3)+s(MLDpart,k=3)+s(LSTlarv,k=3), data=dat)
best_lm<-lm(Y_rec~ONIpre+CutiSTIpjuv+I(CutiSTIpjuv)^2+LSTlarv+MLDlarv, data=dat)
vif(best)
summary(best_lm)
plot.gam(best)
draw(best, transform = "response", cex = 2)
